/**
 * spotProfiles.js — Spot profile data for WavePreview (Surf Mode)
 *
 * This provides the SPOT_PROFILES shape that WavePreview.jsx expects.
 * WaveEngine uses WaveSpotProfiles.js (WAVE_SPOTS) which has a different shape.
 */

export const SPOT_PROFILES = {
  pipeline: {
    name: 'Pipeline',
    region: 'North Shore, Oahu',
    waveHeight: [8, 15],
    faceSteepness: 75,
    waterColor: '#006994',
    waterClarity: 0.8,
    surfaceChop: 0.3,
    barrelDepth: 0.9,
    shoulderLength: 30,
    lipCurlRadius: 0.3,
    foamIntensity: 0.9,
    waveEnergy: 0.95,
    idealBoardTypes: ['performanceShortboard', 'gun'],
  },
  malibu: {
    name: 'Malibu First Point',
    region: 'California',
    waveHeight: [2, 6],
    faceSteepness: 30,
    waterColor: '#2a7f62',
    waterClarity: 0.5,
    surfaceChop: 0.15,
    barrelDepth: 0.05,
    shoulderLength: 60,
    lipCurlRadius: 0.9,
    foamIntensity: 0.3,
    waveEnergy: 0.3,
    idealBoardTypes: ['longboard', 'midLength', 'fish'],
  },
  trestles: {
    name: 'Lower Trestles',
    region: 'San Clemente, CA',
    waveHeight: [3, 8],
    faceSteepness: 50,
    waterColor: '#1a759f',
    waterClarity: 0.6,
    surfaceChop: 0.2,
    barrelDepth: 0.2,
    shoulderLength: 35,
    lipCurlRadius: 0.6,
    foamIntensity: 0.5,
    waveEnergy: 0.65,
    idealBoardTypes: ['performanceShortboard', 'groveler'],
  },
  teahupoo: {
    name: "Teahupo'o",
    region: 'Tahiti',
    waveHeight: [6, 20],
    faceSteepness: 85,
    waterColor: '#0077b6',
    waterClarity: 0.9,
    surfaceChop: 0.2,
    barrelDepth: 1.0,
    shoulderLength: 20,
    lipCurlRadius: 0.15,
    foamIntensity: 0.95,
    waveEnergy: 1.0,
    idealBoardTypes: ['gun'],
  },
  rincon: {
    name: 'Rincon',
    region: 'Santa Barbara, CA',
    waveHeight: [3, 8],
    faceSteepness: 40,
    waterColor: '#3d6b7f',
    waterClarity: 0.5,
    surfaceChop: 0.2,
    barrelDepth: 0.15,
    shoulderLength: 50,
    lipCurlRadius: 0.7,
    foamIntensity: 0.4,
    waveEnergy: 0.5,
    idealBoardTypes: ['performanceShortboard', 'midLength', 'longboard'],
  },
  hossegor: {
    name: 'Hossegor La Gravière',
    region: 'France',
    waveHeight: [4, 12],
    faceSteepness: 65,
    waterColor: '#1b4965',
    waterClarity: 0.4,
    surfaceChop: 0.35,
    barrelDepth: 0.7,
    shoulderLength: 25,
    lipCurlRadius: 0.4,
    foamIntensity: 0.8,
    waveEnergy: 0.85,
    idealBoardTypes: ['performanceShortboard', 'gun'],
  },
  waikiki: {
    name: 'Waikiki',
    region: 'Honolulu, Hawaii',
    waveHeight: [1, 4],
    faceSteepness: 20,
    waterColor: '#48cae4',
    waterClarity: 0.85,
    surfaceChop: 0.1,
    barrelDepth: 0.0,
    shoulderLength: 80,
    lipCurlRadius: 0.95,
    foamIntensity: 0.15,
    waveEnergy: 0.2,
    idealBoardTypes: ['longboard', 'midLength', 'fish', 'groveler'],
  },
  cloudbreak: {
    name: 'Cloudbreak',
    region: 'Fiji',
    waveHeight: [5, 15],
    faceSteepness: 70,
    waterColor: '#0096c7',
    waterClarity: 0.85,
    surfaceChop: 0.25,
    barrelDepth: 0.85,
    shoulderLength: 60,
    lipCurlRadius: 0.3,
    foamIntensity: 0.85,
    waveEnergy: 0.9,
    idealBoardTypes: ['performanceShortboard', 'gun'],
  },
};
