/**
 * WaveSpotProfiles.js — Spot configuration for the GLB-based wave engine
 *
 * All 8 spots use the SAME GLB mesh at different scales and colors.
 * Scale maps wave height to mesh size (mesh Y range = 0.45 units).
 */

export const WAVE_SPOTS = {
  pipeline: {
    name: 'Pipeline',
    region: 'North Shore, Oahu',
    scale: 15,
    deepColor: '#001520',
    shallowColor: '#0096c7',
    description: 'Heavy, thick-lipped barrel breaking over shallow reef.',
    waveHeightFt: 14,
    breakType: 'Barreling',
    waveSpeedMS: 8,
    rideDurationS: 12,
  },
  teahupoo: {
    name: "Teahupo'o",
    region: 'Tahiti',
    scale: 20,
    deepColor: '#011845',
    shallowColor: '#0077b6',
    description: "The heaviest wave on earth. Mutant thick lip over dry reef.",
    waveHeightFt: 15,
    breakType: 'Barreling',
    waveSpeedMS: 10,
    rideDurationS: 6,
  },
  cloudbreak: {
    name: 'Cloudbreak',
    region: 'Fiji',
    scale: 14,
    deepColor: '#011845',
    shallowColor: '#0096c7',
    description: 'Long barreling left over coral reef. Holds massive size.',
    waveHeightFt: 10,
    breakType: 'Barreling',
    waveSpeedMS: 9,
    rideDurationS: 12,
  },
  hossegor: {
    name: 'Hossegor La Gravière',
    region: 'France',
    scale: 11,
    deepColor: '#0d1f2b',
    shallowColor: '#3d5a80',
    description: 'Powerful French beach break tubes. Wedgy and punchy.',
    waveHeightFt: 8,
    breakType: 'Barreling',
    waveSpeedMS: 7,
    rideDurationS: 7,
  },
  trestles: {
    name: 'Lower Trestles',
    region: 'San Clemente, CA',
    scale: 8,
    deepColor: '#0d3b4f',
    shallowColor: '#34a0a4',
    description: 'High-performance cobblestone point. Steep enough for airs.',
    waveHeightFt: 5,
    breakType: 'Open face',
    waveSpeedMS: 6,
    rideDurationS: 10,
  },
  rincon: {
    name: 'Rincon',
    region: 'Santa Barbara, CA',
    scale: 8,
    deepColor: '#1a3a3f',
    shallowColor: '#52b69a',
    description: 'Queen of the coast. Long right walls with workable sections.',
    waveHeightFt: 6,
    breakType: 'Open face',
    waveSpeedMS: 5,
    rideDurationS: 12,
  },
  malibu: {
    name: 'Malibu First Point',
    region: 'California',
    scale: 6,
    deepColor: '#0a2618',
    shallowColor: '#40916c',
    description: 'Perfect peeling right. Long walls, mellow pace.',
    waveHeightFt: 4,
    breakType: 'Open face',
    waveSpeedMS: 4,
    rideDurationS: 15,
  },
  waikiki: {
    name: 'Waikiki',
    region: 'Honolulu, Hawaii',
    scale: 4,
    deepColor: '#065a82',
    shallowColor: '#48cae4',
    description: 'Gentle rolling reef break. Where everyone learns to surf.',
    waveHeightFt: 3,
    breakType: 'Open face',
    waveSpeedMS: 3,
    rideDurationS: 20,
  },
};
